POST http://localhost:8080/auction 
Content-Type: application/jsons

{
    "product_name": "Carro",
    "category": "Carro",
    "description": "Carro de testes",
    "condition": 1
}

###
GET http://localhost:8080/auction/62936eed-e225-440f-9a5c-939c844939c8
Content-Type: application/json
